### PR TITLE
ci(release): upgrade cosign-installer action to 3.3.0

### LINKED ISSUE #10: Cosign installer fails during container image sigining in release pipeline
**Describe the bug**

The `sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 #v3.0.1` action now fails during the `relaase` Github workflow, logging:

```
 INFO: Downloading bootstrap version 'v2.0.0' of cosign to verify version to be installed...
      https://storage.googleapis.com/cosign-releases/v2.0.0/cosign-linux-amd64
```

**How to reproduce it**

Publish a new `^v.+` Git tag.

**Expected behaviour**

The installer action to install Cosign. 

**Screenshots**

NA

**Environment**

NA

**Additional context**

NA

### PR DESCRIPTION
**Pull request by maxgio92**
Fixes #10

### CODE REVIEW

**Comment by maxgio92** [comment]
After this we need to release v0.2.0 as binary and OCI image.
cc @FedeDP

**Comment by maxgio92** [comment]
See https://github.com/falcosecurity/peribolos-syncer/pull/13 to allow the CI to pass.
cc @FedeDP

**Comment by FedeDP** [comment]
Will approve after the rebase!

**Comment by maxgio92** [comment]
The PR is now ready @FedeDP, thank you!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
